### ISSUE TITLE
Missing some data file list...

### ISSUE THREAD

**Issue by Chaotic-chaos** [PunkMale/OR-Gate#1]
Hi, there👋.
Thanks for this brilliant work.
I am trying to re-produce the result which described in the paper. But I find it difficult to locate some files listed blow which shown in `required_data.sh`:
  - /home/fangzh21/data/voxceleb/veri_test2.txt;
  - /home/fangzh21/data/voxceleb/list_test_all2.txt;
  - /home/fangzh21/data/voxceleb/list_test_hard2.txt.
 
Thanks for the help! Really looking forward to the reply!

**Comment by PunkMale** [comment]
Hi, thanks for your interest🤗, the test file is available at https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1.html.
Specific URL:
https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt
https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_hard2.txt
https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/list_test_all2.txt
Hope this helps.

**Comment by Chaotic-chaos** [comment]
Wow, that's a really fast response!
Well, it's very helpful, thanks so much for that~
